import Head from "next/head";
import Link from "next/link";
import { useState } from "react";

export async function getServerSideProps({ query }) {
  const data = await fetch(
    `https://dummyjson.com/products/search?q=${query?.search || ""}`
  ).then((res) => res.json());

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  const [search, setSearch] = useState("");
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input
          type="text"
          value={search}
          onChange={(e) => setSearch(e.target.value)}
        />
        <Link href={`/?search=${search}`}>search</Link>
        <ul>
          {data.products.map(({ id, title, price }) => (
            <li key={id}>
              {title} - {price}€
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
