import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";

export async function getServerSideProps({ query }) {
  const data = await fetch(
    `https://dummyjson.com/products/search?q=${query?.search || ""}`
  ).then((res) => res.json());

  return {
    props: { data },
  };
}

export default function Home({ data }) {
  const [searching, setSearching] = useState(false);
  const [timeout, setTimeoutState] = useState(null);
  const router = useRouter();

  function searchProduct(search) {
    router.push(`/?search=${search}`);
    setSearching(false);
  }

  function handleSearch(e) {
    setSearching(true);
    if (timeout) clearTimeout(timeout);
    setTimeoutState(setTimeout(() => searchProduct(e.target.value), 300));
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <input type="text" onChange={handleSearch} />
        {searching ? "🔍" : ""}
        <ul>
          {data.products.map(({ id, title, price }) => (
            <li key={id}>
              {title} - {price}€
            </li>
          ))}
        </ul>
      </main>
    </>
  );
}
